### ISSUE TITLE
Create consistent & explicit way to define "unknown" vs "none" for equipment

### ISSUE THREAD

**Issue by jefffriesen** [RadiantLabs/modeling-api-docs#16]
From user comment:
> Other errors appear to be a result of the API not accepting an empty array for appliances. I don't believe this will be a blocker for us as we can exclude sending this data if we don't have it, but I would think that this should be consistent across the API from a validation standpoint. As an example, if a pass an empty array to hvacHeatingSystems, no errors are raised, but if I do this for cookingRanges, clothesDryers, I receive an error. For cookingRanges and clothesDryers, I get an error that says "Only one [Insert Appliance Name] is allowed" for each appliance respectively.

This is a WIP

**Comment by kloconnell** [comment]
This is resolved in the documentation, but is still a WIP in the codebase.

**Comment by jefffriesen** [comment]
This is fix in documentation and in code. See this section of the docs: https://docs.radiantlabs.co/projects/modeling-api/en/latest/defaulting_engine.html#

**Comment by jefffriesen** [comment]
So defining an empty array tells us that there is no equipment. Right now we are limited to a single item in that array but that will expand over time.
