### ISSUE TITLE
Allow foundation wall height of zero when type is Slab

### ISSUE THREAD

**Issue by joshuamzm** [RadiantLabs/modeling-api-docs#23]
Can we allow `foundations.wallHeight` of `0` when `foundations.type` is `slab`?

![image](https://github.com/RadiantLabs/modeling-api-docs/assets/10285345/0befc2a3-65f6-4840-b259-ba4636f129d3)

**Comment by kloconnell** [comment]
@joshuamzm good question! I think my original intention was that wallHeight would be undefined if there are no foundation walls, but I'm okay with 0 too.
