### ISSUE TITLE
HPXML Generation Error

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#27]
We seem to be getting the error below pretty consistently. I've made 3-5 requests today that have received this error. I've included a single example of a request below that has resulted in this response.

### Request ###

```
{
    "addressFull":"4146 W Desert Hills Dr, Phoenix, AZ 85029-2911",
    "addressComponents":{
       "addressLine1":"4146 W Desert Hills Dr",
       "city":"Phoenix",
       "stateAbbreviation":"AZ",
       "zipCode": "85029-2911"
    },
    "globalControls": {
        "includeTypical": true,
        "resolution": ["annual","monthly"],
        "timelineStartDate": "2023-09-01",
        "timelineDurationInYears": 1
    },
    "baseBuilding":{
       "systems":{
          "hvac":{
            "hvacHeatingSystems": [
                 {
                     "id": "heating-system-1",
                     "systemType": "furnace",
                     "fuel": "natural gas",
                     "heatLoadPercentage": 1,
                     "connectedDistributionId": "distribution-system-1"
                 }
                ],
            "hvacCoolingSystems": [
                 {
                     "id": "cooling-system-1",
                     "systemType": "central air conditioner",
                     "coolLoadPercentage": 1,
                     "connectedDistributionId": "distribution-system-1"
                 }
             ],
             "hvacDistributionSystems": {
                 "airDistributionSystems": [
                     {
                         "id": "distribution-system-1",
                         "systemType": "regular velocity",
                         "ducts": [
                            {
                             "id": "duct-1",
                             "systemType": "supply"
                            },
                            {
                             "id": "duct-2",
                             "systemType": "return"
                            }
                         ]
                     }
                 ]
             }
          }
       }
    }
}
```

### Error ###

```
"errors":[{"message":"\"{\\\"code\\\":3,\\\"error\\\":\\\"Validation and/or XML Path Failure(s) - See individual packages for more information\\\",\\\"stack\\\":\\\"Error: Validation and/or XML Path Failure(s) - See individual packages for more information\\\\n    at checkPreModelingPackagesForErrors (/app/dist/utils/check-pre-modeling-packages-for-errors.js:14:15)\\\\n    at generateHpxmlAndSaveToFile (/app/dist/cli-generate-hpxml-files.js:106:62)\\\"}\"","code":"error-generating-hpxml"}]}
```

**Comment by jefffriesen** [comment]
@lukeduran we've had good conversations about this ticket internally today. Still working on it.

**Comment by lukeduran** [comment]
Any updates on this @jefffriesen? This still seems to be an issue.

**Comment by kloconnell** [comment]
We have discussed this issue internally and identified the cause. It is going to take us a couple days to get that into production, but it is high on our priority list. I will update you when it has been deployed.

**Comment by lukeduran** [comment]
Hi @kellyatradiantlabs,

This still appears to be an issue. Can you provide an update?

**Comment by kloconnell** [comment]
Hi @lukeduran - thanks for your patience on this issue. It is back in our queue and at the top of our list. This was one of those bugs that kept revealing more issues the further we dug in. It has to do with some disconnections between the baseBuilding object and how it is getting mapped into the larger model. We're aiming to have it implemented by the end of next week. cc @joshuamzm

**Comment by lukeduran** [comment]
Hi @kellyatradiantlabs ,

Just wanted to check in on this to see if this had been fixed?

**Comment by jefffriesen** [comment]
@lukeduran this is a work in progress. We're trying to have a fix by end of day Monday but still too soon to be sure. Thanks

**Comment by kloconnell** [comment]
@lukeduran The fix for the bug in this example has been pushed into production. There are some minor associated fixes that are still being worked on, but this address will now model successfully.
